export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  image: string;
  images?: string[];
  category: string;
  brand?: string;
  rating: number;
  reviews: number;
  inStock: boolean;
  discount?: number;
  colors?: string[];
  sizes?: string[];
}

export interface Category {
  id: string;
  name: string;
  image: string;
  productCount: number;
}

export interface User {
  id: string;
  name: string;
  email: string;
  avatar?: string;
}

export const mockCategories: Category[] = [
  { id: '1', name: 'Men', image: 'https://via.placeholder.com/150', productCount: 120 },
  { id: '2', name: 'Women', image: 'https://via.placeholder.com/150', productCount: 180 },
  { id: '3', name: 'Kids', image: 'https://via.placeholder.com/150', productCount: 90 },
  { id: '4', name: 'Accessories', image: 'https://via.placeholder.com/150', productCount: 65 },
  { id: '5', name: 'Shoes', image: 'https://via.placeholder.com/150', productCount: 110 },
  { id: '6', name: 'Sports', image: 'https://via.placeholder.com/150', productCount: 85 },
  { id: '7', name: 'Electronics', image: 'https://via.placeholder.com/150', productCount: 75 },
  { id: '8', name: 'Home & Living', image: 'https://via.placeholder.com/150', productCount: 95 },
  { id: '9', name: 'Beauty', image: 'https://via.placeholder.com/150', productCount: 55 },
  { id: '10', name: 'Jewelry', image: 'https://via.placeholder.com/150', productCount: 45 },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Classic White Shirt',
    description: 'A timeless white shirt perfect for any occasion. Made from premium cotton blend.',
    price: 49.99,
    originalPrice: 79.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300', 'https://via.placeholder.com/300/2', 'https://via.placeholder.com/300/3'],
    category: 'Men',
    brand: 'StyleCo',
    rating: 4.5,
    reviews: 128,
    inStock: true,
    discount: 38,
    colors: ['white', 'blue', 'black'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '2',
    name: 'Summer Floral Dress',
    description: 'Light and breezy floral dress perfect for summer days.',
    price: 89.99,
    originalPrice: 129.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300', 'https://via.placeholder.com/300/2'],
    category: 'Women',
    brand: 'Bella Fashion',
    rating: 4.8,
    reviews: 256,
    inStock: true,
    discount: 31,
    colors: ['floral-pink', 'floral-blue', 'floral-yellow'],
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    id: '3',
    name: 'Denim Jacket',
    description: 'Classic denim jacket with a modern fit. Perfect for layering.',
    price: 129.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300'],
    category: 'Men',
    brand: 'Denim Co',
    rating: 4.6,
    reviews: 89,
    inStock: true,
    colors: ['blue', 'black'],
    sizes: ['M', 'L', 'XL', 'XXL'],
  },
  {
    id: '4',
    name: 'Running Sneakers',
    description: 'High-performance running sneakers with advanced cushioning.',
    price: 159.99,
    originalPrice: 199.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300', 'https://via.placeholder.com/300/2', 'https://via.placeholder.com/300/3', 'https://via.placeholder.com/300/4'],
    category: 'Shoes',
    brand: 'SportMax',
    rating: 4.9,
    reviews: 432,
    inStock: true,
    discount: 20,
    colors: ['white', 'black', 'gray'],
    sizes: ['7', '8', '9', '10', '11', '12'],
  },
  {
    id: '5',
    name: 'Leather Backpack',
    description: 'Premium leather backpack with laptop compartment.',
    price: 199.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300', 'https://via.placeholder.com/300/2'],
    category: 'Accessories',
    brand: 'LuxeBags',
    rating: 4.7,
    reviews: 167,
    inStock: false,
    colors: ['brown', 'black'],
    sizes: [],
  },
  {
    id: '6',
    name: 'Kids T-Shirt Set',
    description: 'Set of 3 colorful t-shirts for kids. 100% organic cotton.',
    price: 34.99,
    originalPrice: 49.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300'],
    category: 'Kids',
    brand: 'KidStyle',
    rating: 4.4,
    reviews: 92,
    inStock: true,
    discount: 30,
    colors: ['red', 'blue', 'green'],
    sizes: ['2T', '3T', '4T', '5T'],
  },
  {
    id: '7',
    name: 'Wool Blazer',
    description: 'Elegant wool blazer for formal occasions.',
    price: 249.99,
    originalPrice: 349.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300', 'https://via.placeholder.com/300/2'],
    category: 'Men',
    brand: 'Executive',
    rating: 4.7,
    reviews: 145,
    inStock: true,
    discount: 29,
    colors: ['navy', 'charcoal', 'black'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '8',
    name: 'Yoga Pants',
    description: 'Comfortable and stretchy yoga pants for your workout.',
    price: 59.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300'],
    category: 'Sports',
    brand: 'FitGear',
    rating: 4.6,
    reviews: 312,
    inStock: true,
    colors: ['black', 'gray', 'navy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: '9',
    name: 'Silk Scarf',
    description: 'Luxurious silk scarf with elegant patterns.',
    price: 79.99,
    originalPrice: 119.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300', 'https://via.placeholder.com/300/2'],
    category: 'Accessories',
    brand: 'Silkline',
    rating: 4.8,
    reviews: 78,
    inStock: true,
    discount: 33,
    colors: ['red', 'blue', 'gold'],
    sizes: [],
  },
  {
    id: '10',
    name: 'Casual Loafers',
    description: 'Comfortable casual loafers for everyday wear.',
    price: 89.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300'],
    category: 'Shoes',
    brand: 'ComfortFit',
    rating: 4.5,
    reviews: 203,
    inStock: true,
    colors: ['brown', 'black', 'tan'],
    sizes: ['7', '8', '9', '10', '11'],
  },
  {
    id: '11',
    name: 'Evening Gown',
    description: 'Stunning evening gown perfect for special occasions.',
    price: 299.99,
    originalPrice: 449.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300', 'https://via.placeholder.com/300/2', 'https://via.placeholder.com/300/3'],
    category: 'Women',
    brand: 'Elegance',
    rating: 4.9,
    reviews: 189,
    inStock: true,
    discount: 33,
    colors: ['black', 'navy', 'burgundy'],
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    id: '12',
    name: 'Kids Sneakers',
    description: 'Fun and colorful sneakers for active kids.',
    price: 44.99,
    originalPrice: 59.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300'],
    category: 'Kids',
    brand: 'PlayTime',
    rating: 4.6,
    reviews: 156,
    inStock: true,
    discount: 25,
    colors: ['pink', 'blue', 'green'],
    sizes: ['1', '2', '3', '4', '5'],
  },
  {
    id: '13',
    name: 'Smart Watch',
    description: 'Feature-rich smart watch with fitness tracking.',
    price: 299.99,
    originalPrice: 399.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300', 'https://via.placeholder.com/300/2'],
    category: 'Electronics',
    brand: 'TechPro',
    rating: 4.7,
    reviews: 523,
    inStock: true,
    discount: 25,
    colors: ['black', 'silver', 'gold'],
    sizes: [],
  },
  {
    id: '14',
    name: 'Throw Pillow Set',
    description: 'Set of 4 decorative throw pillows for your living room.',
    price: 69.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300'],
    category: 'Home & Living',
    brand: 'HomeCraft',
    rating: 4.4,
    reviews: 87,
    inStock: true,
    colors: ['beige', 'gray', 'navy'],
    sizes: [],
  },
  {
    id: '15',
    name: 'Face Cream Set',
    description: 'Complete skincare set with moisturizer and serum.',
    price: 89.99,
    originalPrice: 129.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300', 'https://via.placeholder.com/300/2'],
    category: 'Beauty',
    brand: 'GlowSkin',
    rating: 4.8,
    reviews: 298,
    inStock: true,
    discount: 31,
    colors: [],
    sizes: [],
  },
  {
    id: '16',
    name: 'Gold Necklace',
    description: 'Elegant 18k gold necklace with pendant.',
    price: 499.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300'],
    category: 'Jewelry',
    brand: 'GoldLine',
    rating: 4.9,
    reviews: 67,
    inStock: true,
    colors: ['gold'],
    sizes: [],
  },
  {
    id: '17',
    name: 'Cargo Shorts',
    description: 'Practical cargo shorts with multiple pockets.',
    price: 54.99,
    originalPrice: 74.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300'],
    category: 'Men',
    brand: 'Outdoor Pro',
    rating: 4.5,
    reviews: 134,
    inStock: true,
    discount: 27,
    colors: ['khaki', 'olive', 'navy'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '18',
    name: 'Cardigan Sweater',
    description: 'Cozy cardigan sweater perfect for chilly days.',
    price: 79.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300', 'https://via.placeholder.com/300/2'],
    category: 'Women',
    brand: 'Cozy Wear',
    rating: 4.6,
    reviews: 221,
    inStock: true,
    colors: ['cream', 'gray', 'burgundy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: '19',
    name: 'Tennis Racket',
    description: 'Professional-grade tennis racket for serious players.',
    price: 179.99,
    originalPrice: 229.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300'],
    category: 'Sports',
    brand: 'ProSport',
    rating: 4.8,
    reviews: 167,
    inStock: true,
    discount: 22,
    colors: ['black', 'blue'],
    sizes: [],
  },
  {
    id: '20',
    name: 'Wireless Earbuds',
    description: 'Premium wireless earbuds with noise cancellation.',
    price: 149.99,
    originalPrice: 199.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300', 'https://via.placeholder.com/300/2'],
    category: 'Electronics',
    brand: 'AudioMax',
    rating: 4.7,
    reviews: 412,
    inStock: true,
    discount: 25,
    colors: ['white', 'black'],
    sizes: [],
  },
  {
    id: '21',
    name: 'Designer Sunglasses',
    description: 'Stylish designer sunglasses with UV protection.',
    price: 199.99,
    originalPrice: 299.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300'],
    category: 'Accessories',
    brand: 'LuxShades',
    rating: 4.7,
    reviews: 145,
    inStock: true,
    discount: 33,
    colors: ['black', 'tortoise', 'gold'],
    sizes: [],
  },
  {
    id: '22',
    name: 'Kids Winter Jacket',
    description: 'Warm winter jacket to keep kids cozy.',
    price: 89.99,
    image: 'https://via.placeholder.com/300',
    images: ['https://via.placeholder.com/300'],
    category: 'Kids',
    brand: 'WarmKids',
    rating: 4.7,
    reviews: 178,
    inStock: true,
    colors: ['red', 'blue', 'pink'],
    sizes: ['4', '6', '8', '10', '12'],
  },
];

export const mockUser: User = {
  id: '1',
  name: 'John Doe',
  email: 'john.doe@example.com',
  avatar: 'https://via.placeholder.com/100',
};

// Mock authentication state
export let isAuthenticated = false;

export const setMockAuth = (value: boolean) => {
  isAuthenticated = value;
};
